### ISSUE TITLE
Help pages don't have a "Home" button

### ISSUE THREAD

**Issue by giduac** [Krypton-Suite/Help-Files#6]
To reproduce:

- Go to: https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/index.html

From here you can choose from several options but after that you can never return to the start page.

I think a Home button might be a good addition...

**Comment by PWagner1** [comment]
Hi @giduac 

Been updating https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/index.html over the last few weeks. Please have a fresh look at it again, as it's much more mature now.
